# Generated by Django 5.2 on 2025-05-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, default='Provide a short excerpt here.'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default='mountains.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default='Write your blog post here.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Please add your title', max_length=100),
        ),
    ]
