# Generated by Django 5.2 on 2025-06-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_date_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_email',
            field=models.EmailField(default='email@server.com', max_length=254),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='email@server.com', max_length=254),
        ),
    ]
